prometheus:
  prometheusSpec:
    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 10Gi
          selector:
            matchLabels:
              type: local
              purpose: prometheus
    serviceMonitorSelector:
      matchLabels:
        release: prometheus

grafana:
  deploymentStrategy:
    type: Recreate
  adminPassword: 404NotFound
  persistence:
    type: pvc
    enabled: true
    storageClassName: local
    accessModes:
      - ReadWriteOnce
    size: 10Gi
    finalizers:
      - kubernetes.io/pvc-protection
    selectorLabels:
      type: local
      purpose: grafana