kind: PersistentVolume
apiVersion: v1
metadata:
  name: prometheus-pv
  labels:
    type: local
    purpose: prometheus
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    name: prometheus-prometheus-kube-prometheus-prometheus-db-prometheus-prometheus-kube-prometheus-prometheus-0
    namespace: monitoring
  hostPath:
    path: "/tmp/prometheus0"

---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: grafana-pv
  labels:
    type: local
    purpose: grafana
spec:
  storageClassName: local
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    name: prometheus-grafana
    namespace: monitoring
  hostPath:
    path: "/tmp/grafana0"